=== rohaan2614/dsci_644_assignment_4/part_1_gantt_project/data/xslfo_export/gantt.dtd
<?xml version='1.0' encoding="UTF-8"?>

<!-- ==============================================================================================
This DTD is the description of the XML document format used by the XSLFO to PDF transformation.
Should be used as a reference for creating custom XSL stylesheets.
=============================================================================================== -->

<!-- ResourceChart Information -->
<!ELEMENT xsl:stylesheet (xmlns:xsl, xmlns:ganttproject, version)>

<!-- Root element of the document -->
<!ELEMENT ganttproject:report (#PCDATA)>

<!-- Project information -->
<!ELEMENT ganttproject:project (xslfo-path, title,name,nameValue,organisation,organisationValue,description,descriptionValue)>
<!-- Project attributes -->
<!ELEMENT title (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nameValue (#PCDATA)>
<!ELEMENT organisation (#PCDATA)>
<!ELEMENT organisationValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT descriptionValue (#PCDATA)>

<!-- GanttChart Information -->
<!ELEMENT ganttproject:ganttchart (xslfo-path, title,src)>

<!-- ResourceChart Information -->
<!ELEMENT ganttproject:resourceschart (xslfo-path, title,src)>


<!-- All task of the project -->
<!ELEMENT ganttproject:tasks (#PCDATA|ganttproject:task)*>
<!-- Lozalized versions for attributes -->
<!ATTLIST ganttproject:tasks xslfo-path, CDATA #IMPLIED>
<!ATTLIST ganttproject:tasks title CDATA #IMPLIED>
<!ATTLIST ganttproject:tasks name CDATA #IMPLIED>
<!ATTLIST ganttproject:tasks begin CDATA #IMPLIED>
<!ATTLIST ganttproject:tasks end CDATA #IMPLIED>
<!ATTLIST ganttproject:tasks milestone CDATA #IMPLIED>
<!ATTLIST ganttproject:tasks progress CDATA #IMPLIED>
<!ATTLIST ganttproject:tasks assigned-to CDATA #IMPLIED>
<!ATTLIST ganttproject:tasks notes CDATA #IMPLIED>

<!-- One task -->
<!ELEMENT ganttproject:task (name,begin,end,milestone,progress,assigned-to,notes,color)>
<!-- Task attributes -->
<!ELEMENT begin (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT milestone (#PCDATA)>
<!ELEMENT progress (#PCDATA)>
<!ELEMENT assigned-to (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
<!ELEMENT color (#PCDATA)>


<!-- All resources for the project -->
<!ELEMENT ganttproject:resources (#PCDATA|ganttproject:resource)*>
<!-- XFLFO directory " -->
<!ATTLIST ganttproject:resources xslfo-path, CDATA #IMPLIED>
<!-- Localized version of title for this chapter," -->
<!ATTLIST ganttproject:resources title CDATA #IMPLIED>
<!-- Localized version of "Name" -->
<!ATTLIST ganttproject:resources name CDATA #IMPLIED>
<!-- Localized version of "Role" -->
<!ATTLIST ganttproject:resources role CDATA #IMPLIED>
<!-- Localized version of "Mail" -->
<!ATTLIST ganttproject:resources contact CDATA #IMPLIED>
<!-- Localized version of "Phone" -->
<!ATTLIST ganttproject:resources phone CDATA #IMPLIED>

<!-- One resource description - name, role, contact -->
<!ELEMENT ganttproject:resource (name,role,mail,phone)>
<!-- Role for the resource -->
<!ELEMENT role (#PCDATA)>
<!-- Mail to the resource -->
<!ELEMENT mail (#PCDATA)>
<!-- Phone to the resource -->
<!ELEMENT phone (#PCDATA)>

=== rohaan2614/dsci_644_assignment_4/part_1_gantt_project/data/xslfo_export/gantt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ganttproject SYSTEM "gantt.dtd">
<xsl:stylesheet
        xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
        xmlns:ganttproject="http://ganttproject.sf.net/"
        version="1.0">
 
<ganttproject:report>
 
        <ganttproject:project
								xslfo-path="/home/thomas/xslfodirectory"
                title="GanttProject Report"
                name="Project"
                nameValue="Test project"
                organisation="Organization"
                organisationValue="Some fancy organization"
                description="Description">
                <desctiptionValue>
                        Thorough project description
                </desctiptionValue>
        </ganttproject:project>
 
        <ganttproject:ganttchart 
						title="Gantt Chart" 
						src="/tmp/ganttchart.jpg"
						xslfo-path="/home/thomas/xslfodirectory">
        </ganttproject:ganttchart>
 
        <ganttproject:resourceschart 
						title="Resources Chart" 
						src="/tmp/resourceschart.jpg"
						xslfo-path="/home/thomas/xslfodirectory">
        </ganttproject:resourceschart>
 
        <ganttproject:tasks 
								xslfo-path="/home/thomas/xslfodirectory"
								title="Tasks List"
                name="Name"
                begin="Start"
                end="End"
                milestone="Bilan"
                progress="%"
                assigned-to="Res."
                notes="Notes">
 
                <ganttproject:task>
                        <name>Task1</name>
                        <begin>Sep 21, 2003</begin>
                        <end>Sep 25, 2003</end>
                        <milestone>false</milestone>
                        <progress>0</progress>
                        <assigned-to>&#160;</assigned-to>
                        <notes><![CDATA[ ]]></notes>
                        <color>#8cb6ce</color>
                </ganttproject:task>
                <ganttproject:task>
                        <name>Task2</name>
                        <begin>Sep 11, 2003</begin>
                        <end>Sep 22, 2003</end>
                        <milestone>false</milestone>
                        <progress>0</progress>
                        <assigned-to>&#160;</assigned-to>
                        <notes><![CDATA[ ]]></notes>
                        <color>#8cb6ce</color>
                </ganttproject:task>
 
        </ganttproject:tasks>
 
        <ganttproject:resources 
								xslfo-path="/home/thomas/xslfodirectory"
								title="Resources List"
                name="Name"
                role="Role"
                mail="Mail"
                phone="Phone">
 
                <ganttproject:resource>
                        <name>Person1</name>
                        <role>developer</role>
                        <mail>toto@toto.com</mail>
                        <phone>0878565442</phone>
                </ganttproject:resource>
                <ganttproject:resource>
                        <name>Person2</name>
                        <role>tester</role>
                        <mail>evan@essence.fr</mail>
                        <phone>(+33)984566544</phone>
                </ganttproject:resource>
        </ganttproject:resources>
 
</ganttproject:report>
 
</xsl:stylesheet>
