=== rohaan2614/dsci_644_assignment_4/data/xslt_export/gantt.dtd
<?xml version='1.0' encoding="UTF-8"?>

<!-- ==============================================================================================
This DTD is the description of the XML document format used by the XSL to HTML transformation.
Should be used as a reference for creating custom XSL stylesheets.
=============================================================================================== -->

<!-- Root element of the document -->
<!ELEMENT ganttproject (title,links,project,chart,resources,tasks)>

<!-- Title that will be assigned to the HTML page <title> tag -->
<!ELEMENT title (#PCDATA)>

<!--
	Names for the links to project pages.
	These are NAMES not urls - this names will be visible to the user
-->
<!ELEMENT links (home,chart,tasks,resources)>
<!--
	Prefix for generated html files.
	Say, you put here "myProject", then your html files will be:
		myProject.html
		myProject-chart.html
		myProject-resources.html
		myProject-tasks.html
-->
<!ATTLIST links prefix CDATA #IMPLIED>

<!-- Name for Home link. -->
<!ELEMENT home (#PCDATA)>

<!-- In Links - name for Chart link, in root - path to the png chart file -->
<!ELEMENT chart (#PCDATA)>

<!-- Project description fields: name, organization, description. -->
<!ELEMENT project (name,organization,description)>

<!-- Project name, Resource name -->
<!ELEMENT name (#PCDATA)>
<!-- Localized version of "Project Name" -->
<!ATTLIST name title CDATA #IMPLIED>

<!-- Organization name -->
<!ELEMENT organization (#PCDATA)>
<!-- Localized version of "Organization" -->
<!ATTLIST organization title CDATA #IMPLIED>

<!-- Description name -->
<!ELEMENT description (#PCDATA)>
<!-- Localized version of "Description" -->
<!ATTLIST description title CDATA #IMPLIED>

<!-- All resources for the project -->
<!ELEMENT resources (#PCDATA|resource)*>
<!-- Localized version of "Name" -->
<!ATTLIST resources name CDATA #IMPLIED>
<!-- Localized version of "Role" -->
<!ATTLIST resources role CDATA #IMPLIED>
<!-- Localized version of "Mail" -->
<!ATTLIST resources mail CDATA #IMPLIED>
<!-- Localized version of "Phone" -->
<!ATTLIST resources phone CDATA #IMPLIED>

<!-- One resource description - name, role, contact -->
<!ELEMENT resource (name,role,mail,phone)>
<!-- Role for the resource -->
<!ELEMENT role (#PCDATA)>
<!-- Mail to the resource -->
<!ELEMENT mail (#PCDATA)>
<!-- Phone to the resource -->
<!ELEMENT phone (#PCDATA)>

<!-- All task of the project -->
<!ELEMENT tasks (#PCDATA|task)*>
<!-- Lozalized versions for attributes -->
<!ATTLIST tasks name CDATA #IMPLIED>
<!ATTLIST tasks begin CDATA #IMPLIED>
<!ATTLIST tasks end CDATA #IMPLIED>
<!ATTLIST tasks milestone CDATA #IMPLIED>
<!ATTLIST tasks progress CDATA #IMPLIED>
<!ATTLIST tasks assigned-to CDATA #IMPLIED>
<!ATTLIST tasks notes CDATA #IMPLIED>

<!-- One task -->
<!ELEMENT task (name,begin,end,milestone,progress,assigned-to,notes)>
<!-- Task attributes -->
<!ELEMENT begin (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT milestone (#PCDATA)>
<!ELEMENT progress (#PCDATA)>
<!ELEMENT assigned-to (#PCDATA)>
<!ELEMENT notes (#PCDATA)>

<!-- footer used for display ganttproject version number and date/time -->
<!ELEMENT footer (version,date)>

=== rohaan2614/dsci_644_assignment_4/part_1_gantt_project/data/xslt_export/gantt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ganttproject SYSTEM "gantt.dtd">
<ganttproject>
	<title>GanttProject - Test project</title>
	<links prefix="gantt">
		<home>Home</home>
		<chart>Chart</chart>
		<tasks>Tasks</tasks>
		<resources>Resources</resources>
	</links>
	<project>
		<name title="Project Name">Test project</name>
		<organization title="Organization">Some fancy organization</organization>
		<description title="Description">Thorough project description</description>
	</project>
	<chart>gantt.png</chart>
	<resources name="Human" role="Role" contact="Contact">
		<resource>
			<name>person1</name>
			<role>role1</role>
			<contact>person1@com.com</contact>
		</resource>
		<resource>
			<name>person2</name>
			<role>role2</role>
			<contact>person2@com.com</contact>
		</resource>
		<resource>
			<name>person3</name>
			<role>role2</role>
			<contact>person3@com.com</contact>
		</resource>
		<chart path="gantt-res.png"/>
	</resources>
	<tasks name="name" begin="Beginning of task" end="End of task" milestone="Milestone" progress="Advancement" assigned-to="Assigned to" notes="Task notes">
		<task>
			<name>Sophisticated task</name>
			<begin>Aug 19, 2003</begin>
			<end>Aug 20, 2003</end>
			<milestone>true</milestone>
			<progress>50%</progress>
			<assigned-to>person1</assigned-to>
			<notes><![CDATA[Aug 19, 2003 - 6:45:10 PM
-------------------------------
test notes]]></notes>
		</task>
		<task>
			<name>Easy one</name>
			<begin>Aug 20, 2003</begin>
			<end>Aug 21, 2003</end>
			<milestone>false</milestone>
			<progress>10%</progress>
			<assigned-to>person2</assigned-to>
			<notes><![CDATA[Aug 20, 2003 - 6:45:10 PM
-------------------------------
blahblah]]></notes>
		</task>
	</tasks>
	<footer version="Ganttproject (1.9.9)" date="21/09/2003 - 21:14"/>
</ganttproject>
